import { Inter } from "next/font/google";
import "./globals.css";
import Link from 'next/link';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="navbar">
          <Link href = "/" className="logo">자유게시판</Link>
          <Link href = "/list">글 목록</Link>
          <Link href = "/write">글 작성</Link>
        </div>
        {children}
      </body>
    </html>
  );
}
